# Generated by Django 5.1.7 on 2025-04-28 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('explanation', models.TextField()),
            ],
            options={
                'db_table': 'concept',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('prerequisites', models.TextField()),
                ('about', models.TextField()),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='CourseConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.concept')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.course')),
            ],
            options={
                'db_table': 'course_concept',
                'unique_together': {('course', 'concept')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='concepts',
            field=models.ManyToManyField(through='recommender.CourseConcept', to='recommender.concept'),
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommender.field')),
            ],
            options={
                'db_table': 'field',
            },
        ),
        migrations.AddField(
            model_name='concept',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommender.field'),
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_time', models.DateTimeField()),
                ('order', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.user')),
            ],
            options={
                'db_table': 'user_course',
                'ordering': ['order'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(through='recommender.UserCourse', to='recommender.course'),
        ),
        migrations.CreateModel(
            name='ConceptFieldRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.ForeignKey(db_column='concept_id', on_delete=django.db.models.deletion.CASCADE, to='recommender.concept')),
                ('field', models.ForeignKey(db_column='field_id', on_delete=django.db.models.deletion.CASCADE, to='recommender.field')),
            ],
            options={
                'db_table': 'concept_field_relation',
                'unique_together': {('concept', 'field')},
            },
        ),
        migrations.CreateModel(
            name='ParentSonRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(db_column='parent_id', on_delete=django.db.models.deletion.CASCADE, related_name='children', to='recommender.concept')),
                ('son', models.ForeignKey(db_column='son_id', on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='recommender.concept')),
            ],
            options={
                'db_table': 'parent_son_relation',
                'indexes': [models.Index(fields=['parent'], name='parent_son__parent__0f2248_idx'), models.Index(fields=['son'], name='parent_son__son_id_8f8e60_idx')],
            },
        ),
        migrations.CreateModel(
            name='PrerequisiteDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='recommender.concept')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='recommender.concept')),
            ],
            options={
                'db_table': 'prerequisite_dependency',
                'unique_together': {('prerequisite', 'target')},
            },
        ),
    ]
