# Generated by Django 4.2.20 on 2025-05-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concept',
            options={'verbose_name': '知识概念', 'verbose_name_plural': '知识概念'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程信息', 'verbose_name_plural': '课程信息'},
        ),
        migrations.AlterModelOptions(
            name='courseconcept',
            options={'verbose_name': '课程-概念关系', 'verbose_name_plural': '课程-概念关系'},
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'verbose_name': '学科领域', 'verbose_name_plural': '学科领域'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AddField(
            model_name='concept',
            name='dependency_count',
            field=models.IntegerField(default=0, help_text='被其他概念作为直接先修条件的次数（实时统计）', verbose_name='被依赖次数'),
        ),
        migrations.AddField(
            model_name='concept',
            name='depth',
            field=models.IntegerField(default=0, help_text='从根领域到当前概念的最长路径深度（自动计算）', verbose_name='层级深度'),
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.FloatField(default=1.0, help_text='基于关联概念平均深度计算的难度系数（周更新）', verbose_name='课程难度'),
        ),
        migrations.AddField(
            model_name='course',
            name='popularity',
            field=models.IntegerField(default=0, help_text='基于用户学习次数计算的课程热度（每日更新）', verbose_name='课程热度'),
        ),
        migrations.AddField(
            model_name='course',
            name='video_name',
            field=models.JSONField(default=list, help_text='课程包含的教学视频名称有序列表，格式示例：["视频1", "视频2", ...]', verbose_name='教学视频序列'),
        ),
        migrations.AddField(
            model_name='courseconcept',
            name='normalized_weight',
            field=models.FloatField(default=0.0, help_text='综合领域深度和被依赖次数的归一化权重（0.0~1.0）', verbose_name='归一化权重'),
        ),
        migrations.AddField(
            model_name='user',
            name='learning_style',
            field=models.JSONField(blank=True, help_text='用户历史学习领域分布的概率向量（格式：{"领域名": 概率值}）', null=True, verbose_name='学习风格向量'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['depth'], name='concept_depth_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['dependency_count'], name='concept_dependency_idx'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['name'], name='field_name_3b7126_idx'),
        ),
    ]
