# Generated by Django 4.2.20 on 2025-05-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_alter_concept_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='entropy_weight',
            field=models.FloatField(default=0.0, help_text='通过熵权法计算的客观权重（自动更新）', verbose_name='熵权法权重'),
        ),
        migrations.AddField(
            model_name='concept',
            name='topsis_score',
            field=models.FloatField(default=0.0, help_text='基于熵权的TOPSIS综合评分（0-1）', verbose_name='TOPSIS评分'),
        ),
    ]
