# Generated by Django 4.2.20 on 2025-05-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_concept_entropy_weight_concept_topsis_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='entropy_weight',
            field=models.FloatField(blank=True, default=0.0, help_text='通过熵权法计算的客观权重（自动更新）', verbose_name='熵权法权重'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='topsis_score',
            field=models.FloatField(blank=True, default=0.0, help_text='基于熵权的TOPSIS综合评分（0-1）', verbose_name='TOPSIS评分'),
        ),
    ]
