# Generated by Django 4.2.20 on 2025-05-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_alter_concept_entropy_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enroll_time',
            field=models.JSONField(blank=True, default=list, help_text='用户课程的入学时间列表'),
        ),
        migrations.AddField(
            model_name='user',
            name='learned_concepts',
            field=models.JSONField(blank=True, default=list, help_text='用户已掌握概念ID列表'),
        ),
        migrations.AddField(
            model_name='user',
            name='learned_courses',
            field=models.JSONField(blank=True, default=list, help_text='用户已学习课程ID列表'),
        ),
    ]
