# Generated by Django 4.2.20 on 2025-05-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_user_enroll_time_user_learned_concepts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='abstract_pre_courses',
            field=models.JSONField(blank=True, default=list, help_text='从课程先修字段中提取的候选先修课程列表'),
        ),
        migrations.AddField(
            model_name='user',
            name='match_pre_courses',
            field=models.JSONField(blank=True, default=list, help_text='根据候选课程匹配得到的最合适的先修课程列表'),
        ),
    ]
